name: Common CI/CD

on:
  push:
    branches:
      - "staging"
      - "release/*"
    paths:
      - "common/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.20.0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      
      - name: Install dependencies
        run: pnpm --filter tachi-common... --filter . install 

      - name: Run Tests
        run: pnpm --filter tachi-common test
